apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clipeer0org2.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "clipeer0org2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.clipeer0org2.autoscaling.enabled }}
  replicas: {{ .Values.clipeer0org2.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clipeer0org2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clipeer0org2.labels" . | nindent 8 }}
    spec:
      {{- with .Values.clipeer0org2.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.clipeer0org2.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.clipeer0org2.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.clipeer0org2.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.clipeer0org2.podSecurityContext | nindent 8 }}
      containers:
        - name: clipeer0org2
          stdin: true
          tty: true
          securityContext:
            {{- toYaml .Values.clipeer0org2.securityContext | nindent 12 }}
          image: "{{ .Values.clipeer0org2.image.repository }}:{{ .Values.clipeer0org2.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.clipeer0org2.image.pullPolicy }}
          workingDir: /
          resources:
            {{- toYaml .Values.clipeer0org2.resources | nindent 12 }}
          command: 
          - /bin/bash
          - -c
          - |
            sleep 60
            echo "shell scripts in /join-channel"
            ls -lh /join-channel
            echo "copy scripts to /tmp"
            cp /join-channel/*.sh /tmp
            echo "apply 'chmod +x' to /tmp/*.sh"
            chmod +x /tmp/*.sh
            echo "execute shell scripts now"
            ./tmp/org2join-upd.sh
            sleep infinity
          env:
            - name: ORDERER_CA
              value: {{ .Values.clipeer0org2.envVars.ORDERER_CA | quote }}
            - name: CORE_PEER_ADDRESS
              value: {{ include "peer0org2.fullname" . }}:7051
            - name: CORE_PEER_ID
              value: {{ .Values.clipeer0org2.envVars.CORE_PEER_ID | quote }}
            - name: CORE_PEER_LOCALMSPID
              value: {{ .Values.clipeer0org2.envVars.CORE_PEER_LOCALMSPID | quote }}
            - name: CORE_PEER_MSPCONFIGPATH
              value: {{ .Values.clipeer0org2.envVars.CORE_PEER_MSPCONFIGPATH | quote }}
            - name: CORE_PEER_TLS_CERT_FILE
              value: {{ .Values.clipeer0org2.envVars.CORE_PEER_TLS_CERT_FILE | quote }}
            - name: CORE_PEER_TLS_ENABLED
              value: {{ .Values.clipeer0org2.envVars.CORE_PEER_TLS_ENABLED | quote }}
            - name: CORE_PEER_TLS_KEY_FILE
              value: {{ .Values.clipeer0org2.envVars.CORE_PEER_TLS_KEY_FILE | quote }}
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: {{ .Values.clipeer0org2.envVars.CORE_PEER_TLS_ROOTCERT_FILE | quote }}
            - name: GOPATH
              value: {{ .Values.clipeer0org2.envVars.GOPATH | quote }}
            - name: SYS_CHANNEL
              value: {{ .Values.clipeer0org2.envVars.SYS_CHANNEL | quote }}
            - name: CORE_CHAINCODE_BUILDER
              value: {{ .Values.clipeer0org2.envVars.CORE_CHAINCODE_BUILDER | quote }}             
            - name: FABRIC_LOGGING_SPEC
              value: {{ .Values.clipeer0org2.envVars.FABRIC_LOGGING_SPEC | quote }}
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /configtx
              name: hlfconfigtx-volume
            - mountPath: /channel-artifacts
              name: fabricfiles
              subPath: channel-artifacts
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
            - mountPath: /opt/gopath/src/github.com/chaincode
              name: hlfchaincode-volume
            - mountPath: /join-channel
              name: joinchannel-config
            - mountPath: /chaincodeids
              name: fabricfiles
              subPath: chaincodeids
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: hlfpvchelm
        - name: hlfchaincode-volume
          configMap:
            name: hlfchaincode
        - name: hlfconfigtx-volume
          configMap:
            name: hlfconfigtx
        - name: joinchannel-config
          configMap:
            name: joinchannel
