apiVersion: v1
kind: Pod
metadata:
  name: inspect
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: hlfpvchelm
    #- name: config
      #configMap:
        #name: hlfcerts
  containers:
    - name: inspection-container
      image: alpine
      command: ["sleep", "infinity"]
      ports:
        - containerPort: 80
          name: "karidopita"
      volumeMounts:
        - mountPath: "/data"
          name: data
        #- name: config
          #mountPath: "/config"
          #readOnly: true
