apiVersion: v1
kind: Service
metadata:
  name: {{ include "orderer2.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "orderer2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orderer2.service.type }}
  ports:
    - port: {{ .Values.orderer2.service.port }}
      targetPort: {{ .Values.orderer2.service.targetPort }}
      protocol: {{ .Values.orderer2.service.protocol }}
      # {{- if and (or (eq .Values.orderer2.service.type "NodePort") (eq .Values.orderer2.service.type "LoadBalancer")) (not (empty .Values.orderer2.service.nodePort)) }}
      # nodePort: {{ .Values.orderer2.service.nodePort }}
      # {{ end }}
  selector:
    {{- include "orderer2.selectorLabels" . | nindent 4 }}
