apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.labels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.api.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          stdin: true
          tty: true
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.containerPort }}
              protocol: {{ .Values.api.service.protocol }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          command:           
          - /bin/sh
          - -c
          - |
            echo "waiting for blockchain deploy"
            sleep 260
            node app.js
            echo "hello?"
          env:
            - name: FABRIC_CA_SERVER_CA_NAME
              value: {{ include "caorg1.fullname" . | quote }}
          volumeMounts:
            - name: fabricfiles
              mountPath: /usr/src/app/connection-profile
              subPath: connection-profile
            - name: fabricfiles
              mountPath: /organizations
              subPath: organizations
            - name: fabricfiles
              mountPath: /components/userWallet/tms
              subPath: wallet
            - name: fabricfiles
              mountPath: /components/adminWallet
              subPath: wallet
            - mountPath: /usr/src/app/config.json
              name: caclientconfig
              subPath: config.json  
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: hlfpvchelm
        - name: caclientconfig
          configMap:
            name: caclientconfig
            items:
              - key: config.json
                path: config.json
                mode: 0544
